- name: Deploy to S3
  uses: aws-actions/s3-upload-action@v2
  with:
    bucket: my-static-website-bucket
    region: us-east-1
    local_dir: build
    acl: public-read
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}