name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install
    - name: Build React app
      run: |
        npm run build
    - name: Deploy to S3
      uses: aws-actions/s3-upload-action@v2
      with:
        bucket: my-static-website-bucket
        region: us-east-1
        local_dir: build
        acl: public-read
    - name: Invalidate CloudFront cache
      uses: aws-actions/cloudfront-invalidate-action@v1
      with:
        distribution-id: my-cloudfront-distribution-id
        paths: '/*'